backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
